version: '3'

services:
  ddrdle-api:
    build: ./
    ports:
      - "8020:5020"
    networks:
      - app_network
    # UNIDEAL
    volumes:
      - ./static:/app/static
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
